# Generated by Django 3.1.4 on 2021-01-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='yang', max_length=100),
            preserve_default=False,
        ),
    ]
